apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: default
spec:
  selector:
    app: python-example
  type: NodePort
  ports:
  - name: python-example-service-port
    port: 5000
    targetPort: 5000 
    protocol: TCP
    nodePort: 30005